version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"

    volumes:
      - .:/app:ro          # код лише на читання
      - dbdata:/data       # RW‑том для SQLite
      - media:/app/media   # медіафайли

volumes:
  dbdata:
  media:
