version: "3.9"

services:
  web:
    image: ghcr.io/shtomuch/univ_django-web:latest   # ← готовий образ
    platform: linux/amd64
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123

    volumes:
      - dbdata:/data        # SQLite та міграції
      - media:/app/media    # user‑content

volumes:
  dbdata:
  media:
