# Generated by Django 4.2.20 on 2025-04-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd_project2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='type',
        ),
    ]
