# Generated by Django 4.2.20 on 2025-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_cd_project2', '0002_remove_good_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='status',
        ),
        migrations.AddField(
            model_name='good',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
