name: Django CI + Publish (GHCR)

on:
  push:
    branches: [ "main" ]         # push у main → тести + push образу
  pull_request:                  # у PR — лише тести

# права для GITHUB_TOKEN
permissions:
  contents: read
  packages: write                # потрібні для push у GHCR

jobs:
# ------------------------------------------------------------
# 1) Build → migrate → test
# ------------------------------------------------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build image (load into runner)
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: local/test-image:latest
          load: true            # образ стане доступним docker run

      - name: Run migrations + tests
        run: |
          docker run --rm local/test-image:latest sh -c "
            python manage.py migrate --noinput &&
            python manage.py test --verbosity 2
          "

# ------------------------------------------------------------
# 2) Publish у GHCR (лише push у main, після зеленої 'test')
# ------------------------------------------------------------
  publish:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # сформуємо назву образу у lower‑case
      - name: Set image name
        id: meta
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/univ_django-web"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"

      # логін у GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # будуємо ще раз і пушимо
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.image }}:latest
            ${{ steps.meta.outputs.image }}:${{ github.sha }}
