name: Django CI + Deploy to Render

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DB_NAME:     ${{ secrets.DB_NAME }}
      DB_USER:     ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST:     ${{ secrets.DB_HOST }}
      DB_PORT:     ${{ secrets.DB_PORT }}
    steps:
      - uses: actions/checkout@v3

      - name: Terminate lingering test DB connections
        run: |
          psql "postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/postgres" \
            -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='test_${{ secrets.DB_NAME }}' AND pid <> pg_backend_pid();"

      - name: Run tests
        run: python manage.py test


  deploy-to-render:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key:    ${{ secrets.RENDER_API_KEY }}
